### ISSUE TITLE
2022 bank holidays

### ISSUE THREAD

**Issue by robbiechicago** [midnite81/bank-holidays#4]
Hi,

The UK Govt bank holidays API is showing dates up to the end of 2022 but the package is returning data to a max date of 2021-12-28.

Thanks.

**Comment by robbiechicago** [comment]
I presume this package is no longer maintained :-(

**Comment by midnite81** [comment]
Hi @robbiechicago. Apologies, I must have missed your original comment. I will check out tomorrow. Might be worth checking that the config file doesn't have an exceptionally big cache-duration as this will prevent it from grabbing data from the government's website.

**Comment by midnite81** [comment]
Hi @robbiechicago, I released version v2.0.2 last night with an updated back up file. I ran some tests today and haven't as yet found that the max function isn't pulling a date in Dec 2022. There could be a number of reasons yours isn't updating. Either the connection to the government website isn't happening, or is firewalled, or the cache is set too large. I'll have a more detailed look early next week but with the backup file up to date in v2.0.2 you should to get all the data you need.

**Comment by robbiechicago** [comment]
Hi Simon - thanks for the update. Will update at my end and see if that helps. Will also make the checks you suggest. 
Cheers.
